import { $Serializable } from "@package/java/io";
import { $ZoneRules } from "@package/java/time/zone";
import { $ChronoLocalDate, $ChronoPeriod, $ChronoZonedDateTime, $Chronology, $IsoChronology, $IsoEra, $ChronoLocalDateTime } from "@package/java/time/chrono";
import { $Stream } from "@package/java/util/stream";
import { $DateTimeFormatter, $TextStyle_ } from "@package/java/time/format";
import { $CharSequence, $Enum, $Comparable } from "@package/java/lang";
import { $List, $Map_, $Locale, $Comparator, $Map, $Set } from "@package/java/util";
import { $TemporalField, $TemporalQuery_, $TemporalAccessor, $TemporalAdjuster, $TemporalAmount, $TemporalAdjuster_, $TemporalAmount_, $Temporal, $TemporalUnit, $ValueRange } from "@package/java/time/temporal";
export * as temporal from "@package/java/time/temporal";
export * as chrono from "@package/java/time/chrono";
export * as format from "@package/java/time/format";
export * as zone from "@package/java/time/zone";

declare module "@package/java/time" {
    export class $Period implements $ChronoPeriod, $Serializable {
        get(arg0: $TemporalUnit): number;
        static of(arg0: number, arg1: number, arg2: number): $Period;
        static from(arg0: $TemporalAmount_): $Period;
        static parse(arg0: $CharSequence): $Period;
        static between(arg0: $LocalDate, arg1: $LocalDate): $Period;
        normalized(): $Period;
        addTo(arg0: $Temporal): $Temporal;
        plusDays(arg0: number): $Period;
        plusYears(arg0: number): $Period;
        plusMonths(arg0: number): $Period;
        subtractFrom(arg0: $Temporal): $Temporal;
        minusDays(arg0: number): $Period;
        minusYears(arg0: number): $Period;
        minusMonths(arg0: number): $Period;
        plus(arg0: $TemporalAmount_): $Period;
        isZero(): boolean;
        getMonths(): number;
        isNegative(): boolean;
        minus(arg0: $TemporalAmount_): $Period;
        getChronology(): $IsoChronology;
        toTotalMonths(): number;
        getDays(): number;
        getUnits(): $List<$TemporalUnit>;
        negated(): $Period;
        multipliedBy(arg0: number): $Period;
        static ofDays(arg0: number): $Period;
        getYears(): number;
        static ofYears(arg0: number): $Period;
        static ofMonths(arg0: number): $Period;
        static ofWeeks(arg0: number): $Period;
        withYears(arg0: number): $Period;
        withMonths(arg0: number): $Period;
        withDays(arg0: number): $Period;
        static ZERO: $Period;
        get zero(): boolean;
        get months(): number;
        get negative(): boolean;
        get chronology(): $IsoChronology;
        get days(): number;
        get units(): $List<$TemporalUnit>;
        get years(): number;
    }
    export class $DayOfWeek extends $Enum<$DayOfWeek> implements $TemporalAccessor, $TemporalAdjuster {
        get(arg0: $TemporalField): number;
        static values(): $DayOfWeek[];
        getLong(arg0: $TemporalField): number;
        static valueOf(arg0: string): $DayOfWeek;
        getValue(): number;
        static of(arg0: number): $DayOfWeek;
        static from(arg0: $TemporalAccessor): $DayOfWeek;
        isSupported(arg0: $TemporalField): boolean;
        query<R>(arg0: $TemporalQuery_<R>): R;
        range(arg0: $TemporalField): $ValueRange;
        getDisplayName(arg0: $TextStyle_, arg1: $Locale): string;
        adjustInto(arg0: $Temporal): $Temporal;
        plus(arg0: number): $DayOfWeek;
        minus(arg0: number): $DayOfWeek;
        static WEDNESDAY: $DayOfWeek;
        static MONDAY: $DayOfWeek;
        static THURSDAY: $DayOfWeek;
        static SUNDAY: $DayOfWeek;
        static TUESDAY: $DayOfWeek;
        static FRIDAY: $DayOfWeek;
        static SATURDAY: $DayOfWeek;
        get value(): number;
    }
    /**
     * Values that may be interpreted as {@link $DayOfWeek}.
     */
    export type $DayOfWeek_ = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
    export class $InstantSource {
        static offset(arg0: $InstantSource_, arg1: $Duration_): $InstantSource;
        static system(): $InstantSource;
        static fixed(arg0: $Instant): $InstantSource;
        static tick(arg0: $InstantSource_, arg1: $Duration_): $InstantSource;
    }
    export interface $InstantSource {
        millis(): number;
        instant(): $Instant;
        withZone(arg0: $ZoneId): $Clock;
    }
    /**
     * Values that may be interpreted as {@link $InstantSource}.
     */
    export type $InstantSource_ = (() => $Instant);
    export class $LocalDate implements $Temporal, $TemporalAdjuster, $ChronoLocalDate, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $ChronoLocalDate): number;
        getLong(arg0: $TemporalField): number;
        format(arg0: $DateTimeFormatter): string;
        static of(arg0: number, arg1: number, arg2: number): $LocalDate;
        static of(arg0: number, arg1: $Month_, arg2: number): $LocalDate;
        static from(arg0: $TemporalAccessor): $LocalDate;
        isSupported(arg0: $TemporalUnit): boolean;
        isSupported(arg0: $TemporalField): boolean;
        static parse(arg0: $CharSequence): $LocalDate;
        static parse(arg0: $CharSequence, arg1: $DateTimeFormatter): $LocalDate;
        "with"(arg0: $TemporalAdjuster_): $LocalDate;
        "with"(arg0: $TemporalField, arg1: number): $LocalDate;
        query<R>(arg0: $TemporalQuery_<R>): R;
        range(arg0: $TemporalField): $ValueRange;
        toEpochSecond(arg0: $LocalTime, arg1: $ZoneOffset): number;
        getYear(): number;
        getMonthValue(): number;
        getDayOfMonth(): number;
        static ofInstant(arg0: $Instant, arg1: $ZoneId): $LocalDate;
        isEqual(arg0: $ChronoLocalDate): boolean;
        static ofEpochDay(arg0: number): $LocalDate;
        adjustInto(arg0: $Temporal): $Temporal;
        withYear(arg0: number): $LocalDate;
        withMonth(arg0: number): $LocalDate;
        withDayOfMonth(arg0: number): $LocalDate;
        withDayOfYear(arg0: number): $LocalDate;
        plusDays(arg0: number): $LocalDate;
        plusYears(arg0: number): $LocalDate;
        plusMonths(arg0: number): $LocalDate;
        plusWeeks(arg0: number): $LocalDate;
        isAfter(arg0: $ChronoLocalDate): boolean;
        isBefore(arg0: $ChronoLocalDate): boolean;
        minusDays(arg0: number): $LocalDate;
        minusYears(arg0: number): $LocalDate;
        minusMonths(arg0: number): $LocalDate;
        minusWeeks(arg0: number): $LocalDate;
        plus(arg0: number, arg1: $TemporalUnit): $LocalDate;
        plus(arg0: $TemporalAmount_): $LocalDate;
        getDayOfWeek(): $DayOfWeek;
        getEra(): $IsoEra;
        isLeapYear(): boolean;
        getDayOfYear(): number;
        static now(arg0: $Clock): $LocalDate;
        static now(arg0: $ZoneId): $LocalDate;
        static now(): $LocalDate;
        until(arg0: $ChronoLocalDate): $Period;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        getMonth(): $Month;
        minus(arg0: number, arg1: $TemporalUnit): $LocalDate;
        minus(arg0: $TemporalAmount_): $LocalDate;
        lengthOfMonth(): number;
        toEpochDay(): number;
        getChronology(): $IsoChronology;
        lengthOfYear(): number;
        static ofYearDay(arg0: number, arg1: number): $LocalDate;
        atTime(arg0: number, arg1: number, arg2: number, arg3: number): $LocalDateTime;
        atTime(arg0: $OffsetTime): $OffsetDateTime;
        atTime(arg0: number, arg1: number, arg2: number): $LocalDateTime;
        atTime(arg0: $LocalTime): $LocalDateTime;
        atTime(arg0: number, arg1: number): $LocalDateTime;
        datesUntil(arg0: $LocalDate, arg1: $Period): $Stream<$LocalDate>;
        datesUntil(arg0: $LocalDate): $Stream<$LocalDate>;
        atStartOfDay(arg0: $ZoneId): $ZonedDateTime;
        atStartOfDay(): $LocalDateTime;
        static MIN: $LocalDate;
        static MAX: $LocalDate;
        static EPOCH: $LocalDate;
        get year(): number;
        get monthValue(): number;
        get dayOfMonth(): number;
        get dayOfWeek(): $DayOfWeek;
        get era(): $IsoEra;
        get leapYear(): boolean;
        get dayOfYear(): number;
        get month(): $Month;
        get chronology(): $IsoChronology;
    }
    export class $ZonedDateTime implements $Temporal, $ChronoZonedDateTime<$LocalDate>, $Serializable {
        withEarlierOffsetAtOverlap(): $ZonedDateTime;
        get(arg0: $TemporalField): number;
        getLong(arg0: $TemporalField): number;
        format(arg0: $DateTimeFormatter): string;
        static of(arg0: $LocalDate, arg1: $LocalTime, arg2: $ZoneId): $ZonedDateTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $ZoneId): $ZonedDateTime;
        static of(arg0: $LocalDateTime, arg1: $ZoneId): $ZonedDateTime;
        static from(arg0: $TemporalAccessor): $ZonedDateTime;
        isSupported(arg0: $TemporalUnit): boolean;
        isSupported(arg0: $TemporalField): boolean;
        static parse(arg0: $CharSequence): $ZonedDateTime;
        static parse(arg0: $CharSequence, arg1: $DateTimeFormatter): $ZonedDateTime;
        "with"(arg0: $TemporalAdjuster_): $ZonedDateTime;
        "with"(arg0: $TemporalField, arg1: number): $ZonedDateTime;
        query<R>(arg0: $TemporalQuery_<R>): R;
        getOffset(): $ZoneOffset;
        range(arg0: $TemporalField): $ValueRange;
        getYear(): number;
        getMonthValue(): number;
        getDayOfMonth(): number;
        getHour(): number;
        getMinute(): number;
        getSecond(): number;
        static ofInstant(arg0: $Instant, arg1: $ZoneId): $ZonedDateTime;
        static ofInstant(arg0: $LocalDateTime, arg1: $ZoneOffset, arg2: $ZoneId): $ZonedDateTime;
        getNano(): number;
        withYear(arg0: number): $ZonedDateTime;
        withMonth(arg0: number): $ZonedDateTime;
        withDayOfMonth(arg0: number): $ZonedDateTime;
        withDayOfYear(arg0: number): $ZonedDateTime;
        withHour(arg0: number): $ZonedDateTime;
        withMinute(arg0: number): $ZonedDateTime;
        withSecond(arg0: number): $ZonedDateTime;
        withNano(arg0: number): $ZonedDateTime;
        truncatedTo(arg0: $TemporalUnit): $ZonedDateTime;
        plusNanos(arg0: number): $ZonedDateTime;
        plusDays(arg0: number): $ZonedDateTime;
        plusMinutes(arg0: number): $ZonedDateTime;
        plusHours(arg0: number): $ZonedDateTime;
        plusYears(arg0: number): $ZonedDateTime;
        plusMonths(arg0: number): $ZonedDateTime;
        plusWeeks(arg0: number): $ZonedDateTime;
        minusDays(arg0: number): $ZonedDateTime;
        minusYears(arg0: number): $ZonedDateTime;
        minusMonths(arg0: number): $ZonedDateTime;
        minusWeeks(arg0: number): $ZonedDateTime;
        minusHours(arg0: number): $ZonedDateTime;
        minusMinutes(arg0: number): $ZonedDateTime;
        minusSeconds(arg0: number): $ZonedDateTime;
        minusNanos(arg0: number): $ZonedDateTime;
        plus(arg0: number, arg1: $TemporalUnit): $ZonedDateTime;
        plus(arg0: $TemporalAmount_): $ZonedDateTime;
        getDayOfWeek(): $DayOfWeek;
        getZone(): $ZoneId;
        getDayOfYear(): number;
        static now(arg0: $Clock): $ZonedDateTime;
        static now(arg0: $ZoneId): $ZonedDateTime;
        static now(): $ZonedDateTime;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        toLocalDate(): $LocalDate;
        toLocalDateTime(): $LocalDateTime;
        toLocalTime(): $LocalTime;
        getMonth(): $Month;
        minus(arg0: $TemporalAmount_): $ZonedDateTime;
        minus(arg0: number, arg1: $TemporalUnit): $ZonedDateTime;
        plusSeconds(arg0: number): $ZonedDateTime;
        static ofLocal(arg0: $LocalDateTime, arg1: $ZoneId, arg2: $ZoneOffset): $ZonedDateTime;
        withZoneSameInstant(arg0: $ZoneId): $ZonedDateTime;
        toOffsetDateTime(): $OffsetDateTime;
        withZoneSameLocal(arg0: $ZoneId): $ZonedDateTime;
        withLaterOffsetAtOverlap(): $ZonedDateTime;
        static ofStrict(arg0: $LocalDateTime, arg1: $ZoneOffset, arg2: $ZoneId): $ZonedDateTime;
        withFixedOffsetZone(): $ZonedDateTime;
        compareTo(arg0: $ChronoZonedDateTime<never>): number;
        toEpochSecond(): number;
        toInstant(): $Instant;
        isEqual(arg0: $ChronoZonedDateTime<never>): boolean;
        isAfter(arg0: $ChronoZonedDateTime<never>): boolean;
        isBefore(arg0: $ChronoZonedDateTime<never>): boolean;
        getChronology(): $Chronology;
        get offset(): $ZoneOffset;
        get year(): number;
        get monthValue(): number;
        get dayOfMonth(): number;
        get hour(): number;
        get minute(): number;
        get second(): number;
        get nano(): number;
        get dayOfWeek(): $DayOfWeek;
        get zone(): $ZoneId;
        get dayOfYear(): number;
        get month(): $Month;
        get chronology(): $Chronology;
    }
    export class $ZoneOffset extends $ZoneId implements $TemporalAccessor, $TemporalAdjuster, $Comparable<$ZoneOffset>, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $ZoneOffset): number;
        getLong(arg0: $TemporalField): number;
        static of(arg0: string): $ZoneOffset;
        static from(arg0: $TemporalAccessor): $ZoneOffset;
        isSupported(arg0: $TemporalField): boolean;
        query<R>(arg0: $TemporalQuery_<R>): R;
        range(arg0: $TemporalField): $ValueRange;
        adjustInto(arg0: $Temporal): $Temporal;
        getTotalSeconds(): number;
        static ofTotalSeconds(arg0: number): $ZoneOffset;
        static ofHoursMinutesSeconds(arg0: number, arg1: number, arg2: number): $ZoneOffset;
        static ofHoursMinutes(arg0: number, arg1: number): $ZoneOffset;
        static ofHours(arg0: number): $ZoneOffset;
        static MIN: $ZoneOffset;
        static UTC: $ZoneOffset;
        static MAX: $ZoneOffset;
        static SHORT_IDS: $Map<string, string>;
        get totalSeconds(): number;
    }
    export class $LocalDateTime implements $Temporal, $TemporalAdjuster, $ChronoLocalDateTime<$LocalDate>, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $ChronoLocalDateTime<never>): number;
        getLong(arg0: $TemporalField): number;
        format(arg0: $DateTimeFormatter): string;
        static of(arg0: number, arg1: $Month_, arg2: number, arg3: number, arg4: number): $LocalDateTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): $LocalDateTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): $LocalDateTime;
        static of(arg0: number, arg1: $Month_, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): $LocalDateTime;
        static of(arg0: number, arg1: $Month_, arg2: number, arg3: number, arg4: number, arg5: number): $LocalDateTime;
        static of(arg0: $LocalDate, arg1: $LocalTime): $LocalDateTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): $LocalDateTime;
        static from(arg0: $TemporalAccessor): $LocalDateTime;
        isSupported(arg0: $TemporalUnit): boolean;
        isSupported(arg0: $TemporalField): boolean;
        static parse(arg0: $CharSequence, arg1: $DateTimeFormatter): $LocalDateTime;
        static parse(arg0: $CharSequence): $LocalDateTime;
        "with"(arg0: $TemporalField, arg1: number): $LocalDateTime;
        "with"(arg0: $TemporalAdjuster_): $LocalDateTime;
        query<R>(arg0: $TemporalQuery_<R>): R;
        range(arg0: $TemporalField): $ValueRange;
        getYear(): number;
        getMonthValue(): number;
        getDayOfMonth(): number;
        getHour(): number;
        getMinute(): number;
        getSecond(): number;
        static ofInstant(arg0: $Instant, arg1: $ZoneId): $LocalDateTime;
        static ofEpochSecond(arg0: number, arg1: number, arg2: $ZoneOffset): $LocalDateTime;
        isEqual(arg0: $ChronoLocalDateTime<never>): boolean;
        getNano(): number;
        adjustInto(arg0: $Temporal): $Temporal;
        withYear(arg0: number): $LocalDateTime;
        withMonth(arg0: number): $LocalDateTime;
        withDayOfMonth(arg0: number): $LocalDateTime;
        withDayOfYear(arg0: number): $LocalDateTime;
        withHour(arg0: number): $LocalDateTime;
        withMinute(arg0: number): $LocalDateTime;
        withSecond(arg0: number): $LocalDateTime;
        withNano(arg0: number): $LocalDateTime;
        truncatedTo(arg0: $TemporalUnit): $LocalDateTime;
        plusNanos(arg0: number): $LocalDateTime;
        plusDays(arg0: number): $LocalDateTime;
        plusMinutes(arg0: number): $LocalDateTime;
        plusHours(arg0: number): $LocalDateTime;
        plusYears(arg0: number): $LocalDateTime;
        plusMonths(arg0: number): $LocalDateTime;
        plusWeeks(arg0: number): $LocalDateTime;
        isAfter(arg0: $ChronoLocalDateTime<never>): boolean;
        isBefore(arg0: $ChronoLocalDateTime<never>): boolean;
        minusDays(arg0: number): $LocalDateTime;
        atZone(arg0: $ZoneId): $ZonedDateTime;
        minusYears(arg0: number): $LocalDateTime;
        minusMonths(arg0: number): $LocalDateTime;
        minusWeeks(arg0: number): $LocalDateTime;
        minusHours(arg0: number): $LocalDateTime;
        minusMinutes(arg0: number): $LocalDateTime;
        minusSeconds(arg0: number): $LocalDateTime;
        minusNanos(arg0: number): $LocalDateTime;
        atOffset(arg0: $ZoneOffset): $OffsetDateTime;
        plus(arg0: $TemporalAmount_): $LocalDateTime;
        plus(arg0: number, arg1: $TemporalUnit): $LocalDateTime;
        getDayOfWeek(): $DayOfWeek;
        getDayOfYear(): number;
        static now(arg0: $Clock): $LocalDateTime;
        static now(arg0: $ZoneId): $LocalDateTime;
        static now(): $LocalDateTime;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        toLocalDate(): $LocalDate;
        toLocalTime(): $LocalTime;
        getMonth(): $Month;
        minus(arg0: $TemporalAmount_): $LocalDateTime;
        minus(arg0: number, arg1: $TemporalUnit): $LocalDateTime;
        plusSeconds(arg0: number): $LocalDateTime;
        toEpochSecond(arg0: $ZoneOffset): number;
        toInstant(arg0: $ZoneOffset): $Instant;
        getChronology(): $Chronology;
        static MIN: $LocalDateTime;
        static MAX: $LocalDateTime;
        get year(): number;
        get monthValue(): number;
        get dayOfMonth(): number;
        get hour(): number;
        get minute(): number;
        get second(): number;
        get nano(): number;
        get dayOfWeek(): $DayOfWeek;
        get dayOfYear(): number;
        get month(): $Month;
        get chronology(): $Chronology;
    }
    export class $OffsetTime implements $Temporal, $TemporalAdjuster, $Comparable<$OffsetTime>, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $OffsetTime): number;
        getLong(arg0: $TemporalField): number;
        format(arg0: $DateTimeFormatter): string;
        static of(arg0: $LocalTime, arg1: $ZoneOffset): $OffsetTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: $ZoneOffset): $OffsetTime;
        static from(arg0: $TemporalAccessor): $OffsetTime;
        isSupported(arg0: $TemporalUnit): boolean;
        isSupported(arg0: $TemporalField): boolean;
        static parse(arg0: $CharSequence): $OffsetTime;
        static parse(arg0: $CharSequence, arg1: $DateTimeFormatter): $OffsetTime;
        "with"(arg0: $TemporalAdjuster_): $OffsetTime;
        "with"(arg0: $TemporalField, arg1: number): $OffsetTime;
        query<R>(arg0: $TemporalQuery_<R>): R;
        getOffset(): $ZoneOffset;
        range(arg0: $TemporalField): $ValueRange;
        toEpochSecond(arg0: $LocalDate): number;
        getHour(): number;
        getMinute(): number;
        getSecond(): number;
        static ofInstant(arg0: $Instant, arg1: $ZoneId): $OffsetTime;
        isEqual(arg0: $OffsetTime): boolean;
        getNano(): number;
        adjustInto(arg0: $Temporal): $Temporal;
        withHour(arg0: number): $OffsetTime;
        withMinute(arg0: number): $OffsetTime;
        withSecond(arg0: number): $OffsetTime;
        withNano(arg0: number): $OffsetTime;
        truncatedTo(arg0: $TemporalUnit): $OffsetTime;
        plusNanos(arg0: number): $OffsetTime;
        plusMinutes(arg0: number): $OffsetTime;
        plusHours(arg0: number): $OffsetTime;
        isAfter(arg0: $OffsetTime): boolean;
        isBefore(arg0: $OffsetTime): boolean;
        minusHours(arg0: number): $OffsetTime;
        minusMinutes(arg0: number): $OffsetTime;
        minusSeconds(arg0: number): $OffsetTime;
        minusNanos(arg0: number): $OffsetTime;
        plus(arg0: number, arg1: $TemporalUnit): $OffsetTime;
        plus(arg0: $TemporalAmount_): $OffsetTime;
        static now(arg0: $Clock): $OffsetTime;
        static now(arg0: $ZoneId): $OffsetTime;
        static now(): $OffsetTime;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        toLocalTime(): $LocalTime;
        minus(arg0: number, arg1: $TemporalUnit): $OffsetTime;
        minus(arg0: $TemporalAmount_): $OffsetTime;
        plusSeconds(arg0: number): $OffsetTime;
        atDate(arg0: $LocalDate): $OffsetDateTime;
        withOffsetSameInstant(arg0: $ZoneOffset): $OffsetTime;
        withOffsetSameLocal(arg0: $ZoneOffset): $OffsetTime;
        static MIN: $OffsetTime;
        static MAX: $OffsetTime;
        get offset(): $ZoneOffset;
        get hour(): number;
        get minute(): number;
        get second(): number;
        get nano(): number;
    }
    export class $Clock implements $InstantSource {
        static systemUTC(): $Clock;
        static offset(arg0: $Clock, arg1: $Duration_): $Clock;
        millis(): number;
        static system(arg0: $ZoneId): $Clock;
        static fixed(arg0: $Instant, arg1: $ZoneId): $Clock;
        instant(): $Instant;
        static systemDefaultZone(): $Clock;
        getZone(): $ZoneId;
        withZone(arg0: $ZoneId): $Clock;
        static tickMillis(arg0: $ZoneId): $Clock;
        static tickSeconds(arg0: $ZoneId): $Clock;
        static tickMinutes(arg0: $ZoneId): $Clock;
        static tick(arg0: $Clock, arg1: $Duration_): $Clock;
        get zone(): $ZoneId;
    }
    export class $OffsetDateTime implements $Temporal, $TemporalAdjuster, $Comparable<$OffsetDateTime>, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $OffsetDateTime): number;
        getLong(arg0: $TemporalField): number;
        format(arg0: $DateTimeFormatter): string;
        static of(arg0: $LocalDate, arg1: $LocalTime, arg2: $ZoneOffset): $OffsetDateTime;
        static of(arg0: $LocalDateTime, arg1: $ZoneOffset): $OffsetDateTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: $ZoneOffset): $OffsetDateTime;
        static from(arg0: $TemporalAccessor): $OffsetDateTime;
        isSupported(arg0: $TemporalField): boolean;
        isSupported(arg0: $TemporalUnit): boolean;
        static parse(arg0: $CharSequence): $OffsetDateTime;
        static parse(arg0: $CharSequence, arg1: $DateTimeFormatter): $OffsetDateTime;
        "with"(arg0: $TemporalField, arg1: number): $OffsetDateTime;
        "with"(arg0: $TemporalAdjuster_): $OffsetDateTime;
        query<R>(arg0: $TemporalQuery_<R>): R;
        getOffset(): $ZoneOffset;
        range(arg0: $TemporalField): $ValueRange;
        toEpochSecond(): number;
        getYear(): number;
        getMonthValue(): number;
        getDayOfMonth(): number;
        getHour(): number;
        getMinute(): number;
        getSecond(): number;
        static ofInstant(arg0: $Instant, arg1: $ZoneId): $OffsetDateTime;
        toInstant(): $Instant;
        isEqual(arg0: $OffsetDateTime): boolean;
        toZonedDateTime(): $ZonedDateTime;
        getNano(): number;
        adjustInto(arg0: $Temporal): $Temporal;
        withYear(arg0: number): $OffsetDateTime;
        withMonth(arg0: number): $OffsetDateTime;
        withDayOfMonth(arg0: number): $OffsetDateTime;
        withDayOfYear(arg0: number): $OffsetDateTime;
        withHour(arg0: number): $OffsetDateTime;
        withMinute(arg0: number): $OffsetDateTime;
        withSecond(arg0: number): $OffsetDateTime;
        withNano(arg0: number): $OffsetDateTime;
        truncatedTo(arg0: $TemporalUnit): $OffsetDateTime;
        plusNanos(arg0: number): $OffsetDateTime;
        plusDays(arg0: number): $OffsetDateTime;
        plusMinutes(arg0: number): $OffsetDateTime;
        plusHours(arg0: number): $OffsetDateTime;
        plusYears(arg0: number): $OffsetDateTime;
        plusMonths(arg0: number): $OffsetDateTime;
        plusWeeks(arg0: number): $OffsetDateTime;
        isAfter(arg0: $OffsetDateTime): boolean;
        isBefore(arg0: $OffsetDateTime): boolean;
        minusDays(arg0: number): $OffsetDateTime;
        minusYears(arg0: number): $OffsetDateTime;
        minusMonths(arg0: number): $OffsetDateTime;
        minusWeeks(arg0: number): $OffsetDateTime;
        minusHours(arg0: number): $OffsetDateTime;
        minusMinutes(arg0: number): $OffsetDateTime;
        minusSeconds(arg0: number): $OffsetDateTime;
        minusNanos(arg0: number): $OffsetDateTime;
        plus(arg0: $TemporalAmount_): $OffsetDateTime;
        plus(arg0: number, arg1: $TemporalUnit): $OffsetDateTime;
        getDayOfWeek(): $DayOfWeek;
        getDayOfYear(): number;
        static now(arg0: $Clock): $OffsetDateTime;
        static now(arg0: $ZoneId): $OffsetDateTime;
        static now(): $OffsetDateTime;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        toLocalDate(): $LocalDate;
        toLocalDateTime(): $LocalDateTime;
        toLocalTime(): $LocalTime;
        getMonth(): $Month;
        minus(arg0: number, arg1: $TemporalUnit): $OffsetDateTime;
        minus(arg0: $TemporalAmount_): $OffsetDateTime;
        plusSeconds(arg0: number): $OffsetDateTime;
        static timeLineOrder(): $Comparator<$OffsetDateTime>;
        withOffsetSameInstant(arg0: $ZoneOffset): $OffsetDateTime;
        withOffsetSameLocal(arg0: $ZoneOffset): $OffsetDateTime;
        atZoneSameInstant(arg0: $ZoneId): $ZonedDateTime;
        atZoneSimilarLocal(arg0: $ZoneId): $ZonedDateTime;
        toOffsetTime(): $OffsetTime;
        static MIN: $OffsetDateTime;
        static MAX: $OffsetDateTime;
        get offset(): $ZoneOffset;
        get year(): number;
        get monthValue(): number;
        get dayOfMonth(): number;
        get hour(): number;
        get minute(): number;
        get second(): number;
        get nano(): number;
        get dayOfWeek(): $DayOfWeek;
        get dayOfYear(): number;
        get month(): $Month;
    }
    export class $Month extends $Enum<$Month> implements $TemporalAccessor, $TemporalAdjuster {
        get(arg0: $TemporalField): number;
        length(arg0: boolean): number;
        static values(): $Month[];
        getLong(arg0: $TemporalField): number;
        static valueOf(arg0: string): $Month;
        getValue(): number;
        static of(arg0: number): $Month;
        static from(arg0: $TemporalAccessor): $Month;
        isSupported(arg0: $TemporalField): boolean;
        query<R>(arg0: $TemporalQuery_<R>): R;
        minLength(): number;
        range(arg0: $TemporalField): $ValueRange;
        getDisplayName(arg0: $TextStyle_, arg1: $Locale): string;
        maxLength(): number;
        adjustInto(arg0: $Temporal): $Temporal;
        plus(arg0: number): $Month;
        minus(arg0: number): $Month;
        firstMonthOfQuarter(): $Month;
        firstDayOfYear(arg0: boolean): number;
        static JANUARY: $Month;
        static JUNE: $Month;
        static MAY: $Month;
        static OCTOBER: $Month;
        static DECEMBER: $Month;
        static MARCH: $Month;
        static FEBRUARY: $Month;
        static AUGUST: $Month;
        static JULY: $Month;
        static SEPTEMBER: $Month;
        static NOVEMBER: $Month;
        static APRIL: $Month;
        get value(): number;
    }
    /**
     * Values that may be interpreted as {@link $Month}.
     */
    export type $Month_ = "january" | "february" | "march" | "april" | "may" | "june" | "july" | "august" | "september" | "october" | "november" | "december";
    export class $Duration implements $TemporalAmount, $Comparable<$Duration>, $Serializable {
        get(arg0: $TemporalUnit): number;
        abs(): $Duration;
        compareTo(arg0: $Duration_): number;
        static of(arg0: number, arg1: $TemporalUnit): $Duration;
        static from(arg0: $TemporalAmount_): $Duration;
        toNanos(): number;
        toMillis(): number;
        static parse(arg0: $CharSequence): $Duration;
        static between(arg0: $Temporal, arg1: $Temporal): $Duration;
        toSeconds(): number;
        getSeconds(): number;
        getNano(): number;
        toMinutes(): number;
        toHours(): number;
        toDays(): number;
        truncatedTo(arg0: $TemporalUnit): $Duration;
        addTo(arg0: $Temporal): $Temporal;
        plusNanos(arg0: number): $Duration;
        plusDays(arg0: number): $Duration;
        plusMinutes(arg0: number): $Duration;
        plusHours(arg0: number): $Duration;
        subtractFrom(arg0: $Temporal): $Temporal;
        minusDays(arg0: number): $Duration;
        minusHours(arg0: number): $Duration;
        minusMinutes(arg0: number): $Duration;
        minusSeconds(arg0: number): $Duration;
        minusNanos(arg0: number): $Duration;
        plus(arg0: $Duration_): $Duration;
        plus(arg0: number, arg1: $TemporalUnit): $Duration;
        isZero(): boolean;
        isNegative(): boolean;
        minus(arg0: $Duration_): $Duration;
        minus(arg0: number, arg1: $TemporalUnit): $Duration;
        isPositive(): boolean;
        plusSeconds(arg0: number): $Duration;
        static ofNanos(arg0: number): $Duration;
        static ofSeconds(arg0: number, arg1: number): $Duration;
        static ofSeconds(arg0: number): $Duration;
        getUnits(): $List<$TemporalUnit>;
        negated(): $Duration;
        plusMillis(arg0: number): $Duration;
        multipliedBy(arg0: number): $Duration;
        static ofDays(arg0: number): $Duration;
        static ofHours(arg0: number): $Duration;
        static ofMinutes(arg0: number): $Duration;
        static ofMillis(arg0: number): $Duration;
        withSeconds(arg0: number): $Duration;
        withNanos(arg0: number): $Duration;
        minusMillis(arg0: number): $Duration;
        dividedBy(arg0: number): $Duration;
        dividedBy(arg0: $Duration_): number;
        toDaysPart(): number;
        toHoursPart(): number;
        toMinutesPart(): number;
        toSecondsPart(): number;
        toMillisPart(): number;
        toNanosPart(): number;
        static ZERO: $Duration;
        get seconds(): number;
        get nano(): number;
        get zero(): boolean;
        get negative(): boolean;
        get positive(): boolean;
        get units(): $List<$TemporalUnit>;
    }
    /**
     * Values that may be interpreted as {@link $Duration}.
     */
    export type $Duration_ = $TemporalAmount;
    export class $LocalTime implements $Temporal, $TemporalAdjuster, $Comparable<$LocalTime>, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $LocalTime): number;
        getLong(arg0: $TemporalField): number;
        format(arg0: $DateTimeFormatter): string;
        static of(arg0: number, arg1: number): $LocalTime;
        static of(arg0: number, arg1: number, arg2: number, arg3: number): $LocalTime;
        static of(arg0: number, arg1: number, arg2: number): $LocalTime;
        static from(arg0: $TemporalAccessor): $LocalTime;
        isSupported(arg0: $TemporalField): boolean;
        isSupported(arg0: $TemporalUnit): boolean;
        static parse(arg0: $CharSequence): $LocalTime;
        static parse(arg0: $CharSequence, arg1: $DateTimeFormatter): $LocalTime;
        "with"(arg0: $TemporalAdjuster_): $LocalTime;
        "with"(arg0: $TemporalField, arg1: number): $LocalTime;
        query<R>(arg0: $TemporalQuery_<R>): R;
        range(arg0: $TemporalField): $ValueRange;
        toEpochSecond(arg0: $LocalDate, arg1: $ZoneOffset): number;
        getHour(): number;
        getMinute(): number;
        getSecond(): number;
        static ofInstant(arg0: $Instant, arg1: $ZoneId): $LocalTime;
        getNano(): number;
        static ofNanoOfDay(arg0: number): $LocalTime;
        adjustInto(arg0: $Temporal): $Temporal;
        withHour(arg0: number): $LocalTime;
        withMinute(arg0: number): $LocalTime;
        withSecond(arg0: number): $LocalTime;
        withNano(arg0: number): $LocalTime;
        truncatedTo(arg0: $TemporalUnit): $LocalTime;
        plusNanos(arg0: number): $LocalTime;
        plusMinutes(arg0: number): $LocalTime;
        plusHours(arg0: number): $LocalTime;
        toNanoOfDay(): number;
        isAfter(arg0: $LocalTime): boolean;
        isBefore(arg0: $LocalTime): boolean;
        minusHours(arg0: number): $LocalTime;
        minusMinutes(arg0: number): $LocalTime;
        minusSeconds(arg0: number): $LocalTime;
        minusNanos(arg0: number): $LocalTime;
        atOffset(arg0: $ZoneOffset): $OffsetTime;
        plus(arg0: $TemporalAmount_): $LocalTime;
        plus(arg0: number, arg1: $TemporalUnit): $LocalTime;
        static now(arg0: $Clock): $LocalTime;
        static now(arg0: $ZoneId): $LocalTime;
        static now(): $LocalTime;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        minus(arg0: number, arg1: $TemporalUnit): $LocalTime;
        minus(arg0: $TemporalAmount_): $LocalTime;
        plusSeconds(arg0: number): $LocalTime;
        toSecondOfDay(): number;
        static ofSecondOfDay(arg0: number): $LocalTime;
        atDate(arg0: $LocalDate): $LocalDateTime;
        static MIN: $LocalTime;
        static NOON: $LocalTime;
        static MAX: $LocalTime;
        static MIDNIGHT: $LocalTime;
        get hour(): number;
        get minute(): number;
        get second(): number;
        get nano(): number;
    }
    export class $Instant implements $Temporal, $TemporalAdjuster, $Comparable<$Instant>, $Serializable {
        get(arg0: $TemporalField): number;
        compareTo(arg0: $Instant): number;
        getLong(arg0: $TemporalField): number;
        static from(arg0: $TemporalAccessor): $Instant;
        isSupported(arg0: $TemporalUnit): boolean;
        isSupported(arg0: $TemporalField): boolean;
        static parse(arg0: $CharSequence): $Instant;
        "with"(arg0: $TemporalField, arg1: number): $Instant;
        "with"(arg0: $TemporalAdjuster_): $Instant;
        query<R>(arg0: $TemporalQuery_<R>): R;
        range(arg0: $TemporalField): $ValueRange;
        static ofEpochMilli(arg0: number): $Instant;
        getEpochSecond(): number;
        static ofEpochSecond(arg0: number): $Instant;
        static ofEpochSecond(arg0: number, arg1: number): $Instant;
        getNano(): number;
        adjustInto(arg0: $Temporal): $Temporal;
        truncatedTo(arg0: $TemporalUnit): $Instant;
        plusNanos(arg0: number): $Instant;
        isAfter(arg0: $Instant): boolean;
        isBefore(arg0: $Instant): boolean;
        atZone(arg0: $ZoneId): $ZonedDateTime;
        minusSeconds(arg0: number): $Instant;
        minusNanos(arg0: number): $Instant;
        atOffset(arg0: $ZoneOffset): $OffsetDateTime;
        plus(arg0: $TemporalAmount_): $Instant;
        plus(arg0: number, arg1: $TemporalUnit): $Instant;
        toEpochMilli(): number;
        static now(): $Instant;
        static now(arg0: $Clock): $Instant;
        until(arg0: $Temporal, arg1: $TemporalUnit): number;
        minus(arg0: number, arg1: $TemporalUnit): $Instant;
        minus(arg0: $TemporalAmount_): $Instant;
        plusSeconds(arg0: number): $Instant;
        plusMillis(arg0: number): $Instant;
        minusMillis(arg0: number): $Instant;
        static MIN: $Instant;
        static MAX: $Instant;
        static EPOCH: $Instant;
        get epochSecond(): number;
        get nano(): number;
    }
    export class $ZoneId implements $Serializable {
        static of(arg0: string, arg1: $Map_<string, string>): $ZoneId;
        static of(arg0: string): $ZoneId;
        static from(arg0: $TemporalAccessor): $ZoneId;
        getId(): string;
        normalized(): $ZoneId;
        static systemDefault(): $ZoneId;
        getRules(): $ZoneRules;
        getDisplayName(arg0: $TextStyle_, arg1: $Locale): string;
        static getAvailableZoneIds(): $Set<string>;
        static ofOffset(arg0: string, arg1: $ZoneOffset): $ZoneId;
        static SHORT_IDS: $Map<string, string>;
        get id(): string;
        get rules(): $ZoneRules;
        static get availableZoneIds(): $Set<string>;
    }
}
